deploy:
  provider: rubygems
  on:
    tags: true
  api_key:
    secure: muauPchi5qeIzBrUoUAwmNqR/ONN+UtHvxHOlS7A3XpaxSPdilQLwqa49pvyKjSA+YXxWDpmMSL0jkCHN3ce4bh/n7+LIKh3QhpOA6IrGlPhzHMI1l+kPf5Nh/EgWNIIZL9iNrEYfhpux3acytc5knMWqhdeK8RVPMlwxQ8f/19A2ayQuG+wE4cJUN6A2uMzSMr+jk+BnksyWzYaNBf+s8KvPr2MTss5Byo6DZNRTHCeXDChPsWGsbrtBTa1deqyzsOpJsiSPJbgrs9yRaX9Eq4IfXNtiFy6rwpvTJr/SJ+IUdtRxu8Fh9QII36JKe6DH56YWG9VrsvkBwhD2U0jskVz/LKucU5jUlvrJQRZyfGLQDMbad10UqRibgH4TEN3alQ2ZYr4oviBErA3IwnPvlYPw8PU2ewe+7JDhfes/R5fZq5zAFaulbEpjGd7QvCT7fzKPlr5PsIOgcoDHOm4mVLI2wAnU6ao9MnilrgghDr26Q47YmFVvaun79p11Ae4hZH8GEUci2c3EE4QV8Fmvewny3f5E26OJPTJCEIvED+V/oImlV67Z7VB23P7I9I6IhiaZMX0NnjHXAy+HZqJTxRqjq8ZZxmzhNcyoIyKofzJaWWlCqXRk+6YdIOzlEjKxqQujG2g8xQniSSdoWSxY9ikLurapUDPvr7CgrVcxfM=
